# Generated by Django 5.1.1 on 2024-09-09 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_alter_customer_record_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_record',
            name='upload_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='customer_record',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=20),
        ),
    ]
